config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  get 'rakuten_look' => 'rakuten#look'
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    get :search, on: :collection
    resources :reviews, only: [:index, :create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # 名前とEメールの空白はNG
  validates :name, presence: true
  validates :email, presence: true

  # 一意性
  validates :name, uniqueness: true
  validates :email, uniqueness: true


  # 画像のattach
  attachment :profile_bg
  attachment :profile_image

  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  # ゲストユーザ
def self.guest
  find_or_create_by(email: 'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
  end
end

# board
has_many :boards, dependent: :destroy

# 星レビュー
has_many :reviews, dependent: :destroy

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザの編集・削除することができません'
    end
  end

# パスワードなしで編集
protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end

end 

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # ①ゲストユーザをDBから取り出す
  # ②存在しなければ、ゲストユーザを作成する
  # ③パスワードはランダムに指定する
  # ④sign_in user でログイン
  # ⑤redirect_toでルートに画面遷移
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザとしてログインしました'
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    user_id = User.find(params[:id]).id
    @user_board = Board.where(user_id: user_id).order(created_at: :desc)
  end

    # フォロー一覧を取得
  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'user-index' %>
<% end %>
<div class="user-index-width">
  <hr>
  <% @users.each do |user|%>
    <div class="user-index-flex">
      <% if user.profile_image.present? %>
        <%= link_to user_path(user) do%>
          <%= attachment_image_tag user,:profile_image,class:'profileImage-index'%>
        <% end %>
      <%else%>
      <%= link_to user_path(user) do%>
        <%= image_tag 'No-Image.png' ,class:'profileImage-index ' %>
      <% end %>
      <% end %>
      <div class="block">
        <%= link_to user_path(user) do%>
          <div class="name-color"><%=user.name%></div>
        <% end %>
        <small class="email-color"><%=user.email%></small><br>
        <div><%=simple_format user.profile%></div>
      </div>
    </div>
    <hr>
  <% end %>
  <nav aria-label="Page navigation example">
    <%= paginate @users %>
  </nav>
</div>

app/views/users/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'user-show' %>
<% end %>
<%= render 'shared/flash_messages'%>
<div class= "margin">
  <div class="center">
    <div class="show-image">
      <%= attachment_image_tag @user,:profile_image, fallback:"No-Image.png",class:'user-image'%>
    </div>
    <div class="show-name">
      <%= @user.name%>
    </div>
    <div class="show-email">
      <% if @user.id == current_user.id %>
          <span><%= @user.email %></span>
      <% end %>
    </div>
    <div class="follow">
      <p class="profile">
        <%= link_to following_user_path(@user),style:'text-decoration:none;' do%>
          <span>フォロー<%= @user.followings.count%></span> 
        <% end %>
          &ensp;  &ensp;  &ensp; 
        <%= link_to followers_user_path(@user),style:'text-decoration:none;' do%>
          <span>フォロワー<%= @user.followers.count%></span>
        <% end %>
      </p>
    </div>
    <div class="show-profile">
      <%=simple_format @user.profile%>
    </div>
    <div class="follow-btn">
      <%= render 'relationships/follow_button', user: @user %>
    </div>
    <div class="show-btn-edit">
      <% if @user.id == current_user.id %>
            <%= link_to 'プロフィールを編集する', edit_user_registration_path ,class:'btn-square',style:'text-decoration: none;'%>
      <% end %>
    </div>
    <hr>
    <div class="text">
      <%= @user.name %>さんが投稿した記事一覧</h2>
    </div>
    <div class="show-board-registration">
      <% @user_board.each do |board| %>
      <hr class="hr">
      <div class="border-show-flex">
        <div class="child-show">
          <%= link_to board_path(board) do %> 
            <%= attachment_image_tag board, :image,fallback: "No-Image.png",class:"show-user-image"%>
          <% end %>
          <div class="show-flex">
            <div class="day">
              <%= board.updated_at.strftime("%Y-%m-%d") %>に投稿</span>
            </div>
            <div class="show-title">
              <%= link_to board_path(board.id)do %>
                <%= board.title%>
              <% end %>
            </div>
          </div>
        </div>
        <div class="tag-board-show">
          <% board.tags.each do |tag|%>
            <span class="badge badge-info"><%= tag.name%></span>
          <% end %>
        </div>
      </div>
      <div class=" front-flex">
        <div class="star-rating">
          <div class=" star-rating-front" style="width: <%= board.review_score_percentage %>%">★★★★★</div>
          <div class=" star-rating-back">★★★★★</div>
        </div>
        <div class="average-score-display">
            <%= board.avg_score %>点(<%= board.reviews.count%>件のレビュー)
        </div>
      </div>
      <div class="review">
        <%= link_to board_reviews_path(board) do%>
          レビューを見る
        <%end%>
        <%= link_to board_path(board) do%>
          レビューを書く
        <%end%>
      </div>
      <hr class="hr">
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'user-index' %>
<% end %>

<h1 class="text-center">フォロー</h1>
<hr>
<% @users.each do |user|%>
  <div class="user-index-flex">
    <% if user.profile_image.present? %>
      <%= link_to user_path(user) do%>
        <%= attachment_image_tag user,:profile_image,class:'profileImage-index'%>
      <% end %>
    <%else%>
    <%= link_to user_path(user) do%>
      <%= image_tag 'No-Image.png' ,class:'profileImage-index ' %>
    <% end %>
    <% end %>
    <div class="block">
      <%= link_to user_path(user) do%>
        <div class="name-color"><%=user.name%></div>
      <% end %>
      <small class="email-color"><%=user.email%></small><br>
      <%=user.profile%>
    </div>
  </div>
  <hr>
<% end %>

app/views/users/show_follower.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'user-index' %>
<% end %>

<h1 class="text-center">フォロワー一覧</h1>
<hr>
<% @users.each do |user|%>
  <div class="user-index-flex">
    <% if user.profile_image.present? %>
      <%= link_to user_path(user) do%>
        <%= attachment_image_tag user,:profile_image,class:'profileImage-index'%>
      <% end %>
    <%else%>
    <%= link_to user_path(user) do%>
      <%= image_tag 'No-Image.png' ,class:'profileImage-index ' %>
    <% end %>
    <% end %>
    <div class="block">
      <%= link_to user_path(user) do%>
        <div class="name-color"><%=user.name%></div>
      <% end %>
      <small class="email-color"><%=user.email%></small><br>
      <%=user.profile%>
    </div>
  </div>
  <hr>
<% end %>