config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  get 'rakuten_look' => 'rakuten#look'
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    get :search, on: :collection
    resources :reviews, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  attachment :image

  validates :title, presence: true
  validates :title, length: { maximum: 20 }  


  has_many :board_details, dependent: :destroy, inverse_of: :board
  has_many :board_materials, dependent: :destroy, inverse_of: :board
  accepts_nested_attributes_for :board_details,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :board_materials,reject_if: :all_blank,allow_destroy: true

  has_many :board_tag_relations,dependent: :delete_all
  has_many :tags, through: :board_tag_relations

  # 星レビュー機能
  has_many :reviews, dependent: :destroy

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f * 100/5
    else
      0.0
    end
  end





end

app/models/board_detail.rb
class BoardDetail < ApplicationRecord
  belongs_to :board
  attachment :image_detail
end

app/models/board_material.rb
class BoardMaterial < ApplicationRecord
  belongs_to :board
end

app/models/board_tag_relation.rb
class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/pcrpositive.rb
class Pcrpositive < ApplicationRecord
  def positive_difference
    # 累計の感染者
    positive = Pcrpositive.all.sum(:positive)
    # 累計の感染者の正規表現
    positive = positive.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
    positive = positive.chop
    positive = positive.chop
  end
end

app/models/pcrtested.rb
require 'active_support/core_ext/numeric/conversions'

class Pcrtested < ApplicationRecord
  def pcrtest_sum
    # 累計のPCR検査数
    pcrtest = Pcrtested.all.sum(:pcrtest)
    pcrtest = pcrtest.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
    pcrtest = pcrtest.chop
    pcrtest = pcrtest.chop
    # pcrtest_num = pcrtest.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
  end
end

app/models/recovery.rb
# require 'active_support/core_ext/numeric/conversions'

class Recovery < ApplicationRecord

  # 1日当たりの回復者
  def recovery_difference
    # 1日あたりの回復者数
    # recovery_today = Recovery.last
    # today = recovery_today.recovery
    today = Recovery.last.recovery

    # 前日までの回復者数
    yesterday = Recovery.all
    yesterday = yesterday[-2]
    yesterday = yesterday.recovery

    # 前日比の計算
    today_num = today.to_i 
    yesterday_num = yesterday.to_i

    difference =  today_num - yesterday_num 
    # difference = difference.to_s
  end

  # カンマ区切り
  def recovery_canma
    recovery = Recovery.last
    recovery = recovery.recovery
    recovery = recovery.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
    # recovery.delete!('.')
  end


end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :board
  validates :score, presence: true
  attachment :review_image



end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :board_tag_relations,dependent: :delete_all
  has_many :boards,through: :board_tag_relations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  # 名前とEメールの空白はNG
  validates :name, presence: true
  validates :email, presence: true

  # 一意性
  validates :name, uniqueness: true
  validates :email, uniqueness: true


  # 画像のattach
  attachment :profile_bg
  attachment :profile_image

  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  # ゲストユーザ
def self.guest
  find_or_create_by(email: 'guest@example.com') do |user|
    user.password = SecureRandom.urlsafe_base64
  end
end

# board
has_many :boards, dependent: :destroy

# 星レビュー
has_many :reviews, dependent: :destroy

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @positive = Pcrpositive.last
    @pcrtest =  Pcrtested.last
    @recovery = Recovery.last
    # recovery = recovery.recovery
    
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    time = Time.now
    time = time.ago(2.days)
    @time = time.strftime("%Y/%m/%d(#{wd[time.wday]})")
    # time = @positive.day
    # @time = time.to_s.gsub(/-/,"/")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_meta.erb
<title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :css %>
    

    <%= Gon::Base.render_data %>
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>  </head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">  
  <head>
    <%= render 'layouts/meta'%>
  </head>

  <body>
    <%= render 'shared/header'%>
    <main role="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

  

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <%= link_to "SONAERU", root_path, class: 'navbar-brand text-light' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <%= link_to '新型コロナ感染状況',charts_index_path,class:'nav-link text-light'%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item ">
            <%= link_to 'ユーザー一覧',users_path,class:'nav-link text-light'%>
          </li>
        <li class="nav-item ">
          <%= link_to '投稿一覧',boards_path,class:'nav-link text-light'%>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li class="nav-item ">
              <%= link_to '新規投稿',new_board_path,class: 'nav-link text-light' %>
            </li>
            <li class="nav-item ">
              <%= link_to 'マイページ',current_user,class: 'nav-link text-light' %>
            </li>
              <li class="nav-item ">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
            </div>
          </div>
        <% else %>
          <li class="nav-item ">
            <%= link_to "ログイン", new_user_session_path,class:"nav-link text-light" %>
          </li>
          <li class="nav-item ">
            <%= link_to "新規登録", new_user_registration_path, class:"nav-link text-light" %>
          </li>
          <li class="nav-item ">
            <%= link_to "簡単ログイン", users_guest_sign_in_path,method: :post, class:"nav-link text-light" ,method: :post%>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>