config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  get 'rakuten_look' => 'rakuten#look'
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }
  root 'homes#index'
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :boards do
    get :search, on: :collection
    resources :reviews, only: [:index, :create]
  end

end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  attachment :image

  validates :title, presence: true
  validates :title, length: { maximum: 20 }  


  has_many :board_details, dependent: :destroy, inverse_of: :board
  has_many :board_materials, dependent: :destroy, inverse_of: :board
  accepts_nested_attributes_for :board_details,reject_if: :all_blank,allow_destroy: true
  accepts_nested_attributes_for :board_materials,reject_if: :all_blank,allow_destroy: true

  has_many :board_tag_relations,dependent: :delete_all
  has_many :tags, through: :board_tag_relations

  # 星レビュー機能
  has_many :reviews, dependent: :destroy

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f * 100/5
    else
      0.0
    end
  end





end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @boards = Board.order(created_at: :desc)
  end

  def search
    params[:title].present?
    @boards = Board.where('title LIKE ?', "%#{params[:title]}%")
    flash.now[:notice] = "「#{params[:title]}」を含む検索結果が#{@boards.count}件ヒットしました"
  end

  def show
    @board= Board.find(params[:id])
    board_id = Board.find(params[:id]).id
    @board_material = BoardMaterial.where(board_id: board_id)
    @board_details = BoardDetail.where(board_id: board_id)
    @review = Review.new
    @reviews = Review.where(board_id: board_id)
    # binding.pry
  end

  def new
    @board = Board.new
    @board.board_details.build
    @board.board_materials.build
  end

  def edit
    @board= Board.find(params[:id])
    board_id = Board.find(params[:id]).id
    @board_material = BoardMaterial.where(board_id: board_id)
    @board_details = BoardDetail.where(board_id: board_id)
    @review = Review.new
    @reviews = Review.where(board_id: board_id)
  end

  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    if @board.save
      flash[:notice] = '投稿が完了しました' 
      redirect_to user_path(@board.user_id)
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def update
    @board= Board.find(params[:id])
    @board.update(board_params)
      flash[:notice] = '更新が完了しました' 
      redirect_to user_path(@board.user_id)
  end

  def destroy
    @board= Board.find(params[:id])
    @board.user_id = current_user.id
    if  @board.destroy
      redirect_to user_path(@board.user_id),notice:'削除に成功しました'
    else
      render :show
    end
  end

  private

  def board_params
    params.require(:board).permit(:title,:image,:reason,:point, tag_ids: [],board_details_attributes: [:id, :body, :image_detail, :_destroy],board_materials_attributes: [:id, :material, :quantity, :_destroy])
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board_detail_fields.html.erb
<div class="nested-fields add-detail">
    <div class="imgPreview">
        <%= f.text_area:body,class:'body',rows:3,cols:1,:placeholder => "説明文を入力"  %><br>
        <div id="add-image_0" class="add-relative image-add"> 
          <%= link_to '写真を載せる',class:'add-image',id:'image-preview'%>
        </div> 
            <%= f.attachment_field :image_detail, class: "imageFile",id:"imageFile_0"%>
        <div class="flex-delete-image">
          <%= link_to_remove_association(f) do%>
            <i class="fas fa-window-close font"></i>    
            <% end %>
        </div>
    </div>
    <%= f.hidden_field :id%>
</div>

<%= javascript_include_tag 'boards_detail_image.js' %>

app/views/boards/_board_material_fields.html.erb
<div class="nested-fields ">
  <div class="material-add box25">
    <div class="material-flex">
        <%= f.text_field:material,class:'text-material',:placeholder => "例)画用紙"  %><br>
    </div>
    <div class="quantity-flex">
        <%= f.text_field:quantity,class:'text',:placeholder => "例)3枚"%><br>
    </div>
    <div class="flex-delete">
      <%= link_to_remove_association(f) do%>
        <i class="fas fa-window-close font"></i>    
      <% end %>
    </div>
  </div>
    <%= f.hidden_field :id%>
</div>

app/views/boards/_form.html.erb
<%=form_with(model: board, local: true) do |f|%>
  <div class="board-title">
    <div class="Heading">
      <p>タイトル</p>
    </div>
    <%= f.text_field :title,class:'nice-textbox',placeholder: 'タイトルを入力してください(20文字)'%>
  </div>
  <div class="Heading">
      <p>写真を載せる</p>
    </div>
  <div id="cover-image" class="relative">
    <% if board.image_id.present? %>
      <%= image_tag attachment_url(board, :image),class:'board-image'%>
    <% else %>
      <%= image_tag 'none_image.png',class:'board-image'%>
    <% end %>
    <i class="fa fa-camera"></i>
  </div>
    <%= f.attachment_field :image %><br>

  <div class="Heading">
    <p>投稿の生い立ち</p>
  </div>
  <div class="text-form">
    <%= f.text_area:reason,class:'body',rows:3,cols:1,:placeholder => "この投稿が生まれたきっかけや敬意を入力しよう"  %>
  </div>

  <hr>

  <div class="material-quantity">
    <div class="name-flex">
      <div class="material-name">
        <p>材料</p>
      </div>
      <div class="quantity-name">
        <p>分量</p>
      </div>
    </div>
    <div class="board_details">
      <%= f.fields_for :board_materials do |df| %>
        <%= render partial: "board_material_fields",locals: {f: df } %>
      <% end %>
    </div>
  </div>

      <%# 追加ボタン %>
      <div class="links">
        <div class="links-width">
          <%= link_to_add_association( '行を追加する', f, :board_materials,class:'btn-squared') %>
        </div>
      </div>

    <div class="Heading">
      <p>作り方</p>
    </div>

    <div class="formImage">
    <%= f.fields_for :board_details do |df| %>
      <%= render partial: "board_detail_fields",locals: {f: df } %>
    <% end %>

    <%# 追加ボタン %>
      <div class="links">
        <div class="links-width">
          <%= link_to_add_association( '行を追加する', f, :board_details,class:'btn-squared')%>
        </div>
      </div>
  </div>
  <div class="Heading">
    <p>一言</p>
  </div>
  <div class="text-form">
    <%= f.text_area:point,class:'body',rows:3,cols:1,:placeholder => "アドバイスなどがあれば記載しよう！"  %>
  </div>
    <div class="Heading">
      <p>タグ</p>
    </div>
  <div class="text-form">
    <div class="checkbox">
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %> 
          <%= tag.label class: '' do %> 
            <%= tag.check_box class: '' %> 
            <%= tag.text %> 
          <% end %> 
      <% end %> 
    </div>
      <%= f.submit class:'form-button' %>
    </div>
  </div>

<% end %>
<%= javascript_include_tag 'boards_image.js' %>

app/views/boards/edit.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'new-board' %>
<% end %>
    <%= render 'shared/flash_messages'%>
      <div class="board-new-background">
        <%= render 'form',board: @board %>
      </div>

app/views/boards/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'index-board' %>
<% end %>

<div class="search">
    <%= form_with url: search_boards_path, id: :form2 ,method: :get, local: true do |f| %>
  <div class="search-position text-right">
      <%= f.text_field :title ,id:'sbox2', placeholder:"タイトルを入力" %>
      <%= button_tag id:'sbtn2'  do %>
        <i class="fa fa-search"></i>
      <% end %>
  </div>
    <% end %>
</div>

<div class="container board-margin">
    <% @boards.each do |board| %>
        <hr class="hr">
            <div class="border-index-flex">
              <div class="child-index">
                <%= link_to user_path(board.user.id) do %> 
                  <%= attachment_image_tag board.user, :profile_image,fallback: "No-Image.png",class:"index-user-image"%>
                <% end %>
                <span class="index-name"><%= link_to board.user.name ,user_path(board.user.id)%>が
                <%= board.updated_at.strftime("%Y-%m-%d") %>に投稿</span>
                <div class="index-title">
                <%= link_to board_path(board.id)do %>
                  <%= board.title%>
                <% end %>
                </div>
                <div class="tag">
                  <% board.tags.each do |tag|%>
                    <span class="badge badge-info"><%= tag.name%></span>
                  <% end %>
                </div>
              </div>
            </div>
              <div class=" front-flex">
                <div class="star-rating">
                  <div class=" star-rating-front" style="width: <%= board.review_score_percentage %>%">★★★★★</div>
                  <div class=" star-rating-back">★★★★★</div>
                </div>
                <div class="average-score-display">
                    <%= board.avg_score %>点(<%= board.reviews.count%>件のレビュー)
                </div>
            </div>
            <div class="review">
            <%= link_to board_path(board) do%>
              レビューを書く
            <%end%>
            
          </div>

          <hr class="hr">
    <% end %>
</div>

app/views/boards/new.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'new-board' %>
<% end %>
    <%= render 'shared/flash_messages'%>
      <div class="board-new-background">
        <%= render 'form',board: @board %>
      </div>

app/views/boards/search.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'index-board' %>
<% end %>

<%= render 'shared/flash_messages'%>

  <div class="search">
    <%= form_with url: search_boards_path, id: :form2 ,method: :get, local: true do |f| %>
  <div class="search-position text-right">
      <%= f.text_field :title ,id:'sbox2', placeholder:"タイトルを入力" %>
      <%= button_tag id:'sbtn2'  do %>
        <i class="fa fa-search"></i>
      <% end %>
  </div>
    <% end %>
</div>
<div class="container board-margin">
  <div class="row">
    <% @boards.each do |board| %>
      <div class="col-md-12">
        <hr class="hr">
            <div class="border-index-flex">
              <div class="child-index">
                <%= link_to user_path(board.user.id) do %> 
                  <%= attachment_image_tag board.user, :profile_image,fallback: "No-Image.png",class:"index-user-image"%>
                <% end %>
                <span class="index-name"><%= link_to board.user.name ,user_path(board.user.id)%>が
                <%= board.updated_at.strftime("%Y-%m-%d") %>に投稿</span>
                <div class="index-title">
                <%= link_to board_path(board.id)do %>
                  <%= board.title%>
                <% end %>
                </div>
                <div class="tag">
                  <% board.tags.each do |tag|%>
                    <span class="badge badge-info"><%= tag.name%></span>
                  <% end %>
                </div>
              </div>
            </div>
              <div class=" front-flex">
              <div class="star-rating">
                <div class=" star-rating-front" style="width: <%= board.review_score_percentage %>%">★★★★★</div>
                <div class=" star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display">
                  <%= board.avg_score %>点(<%= board.reviews.count%>件のレビュー)
              </div>
            </div>
            <div class="review">
            <%= link_to board_reviews_path(board) do%>
              レビューを見る
            <%end%>
            <%= link_to board_path(board) do%>
              レビューを書く
            <%end%>
            
          </div>

          <hr class="hr">
      </div>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'show-board' %>
  <%= stylesheet_link_tag 'reviews' %>
<% end %>

<div class="board-show-background">
  <div class="show-board">
    <div class="show-board-flex">
      <div class="show-board-parent">
        <%= link_to user_path(@board.user.id) do %> 
          <%= attachment_image_tag @board.user, :profile_image,fallback: "No-Image.png",class:"show-user-image"%>
        <% end %>
        <span class="show-board-name">
          <%= link_to @board.user.name ,user_path(@board.user.id)%>が
          <%= @board.updated_at.strftime("%Y-%m-%d") %>に投稿
        </span>
      </div>
      <div class="show-board-child">
        <% @board.tags.each do |tag|%>
          <span class="badge badge-info"><%= tag.name%></span>
        <% end %>
      </div>
    </div>
      <div class="show-board-title">
        <h1><%= @board.title%></h1>
      </div>
      <div class="show-board-image">
        <%= attachment_image_tag @board, :image,class:'show-board-title-image'%>
      </div>
      <div class="border-material">
        <h4>材料</h4>
        <hr class="board-boarder">
        <% @board_material.each do |material|%>
          <div class="material-quantity">
            <div class="material"><%=link_to material.material , controller: "rakuten", action: "look", material: material.material %></div>
            <div class="quantity"><%= material.quantity%></div>
          </div>
          <hr class="board-boarder">
      <% end %>

      <div class="Heading">
        <p>投稿のきっかけ</p>
      </div>

      <div class="show-form">
        <p><%= simple_format @board.reason%></p>
      </div>
      
      <div class="Heading">
        <p>作り方</p>
      </div>
      <% @board_details.each do |board_detail| %>
        <div class="user-show-flex">
          <div class="text-show ">
            <%=simple_format board_detail.body%>
          </div>
          <div class="user-show-image">
            <%= attachment_image_tag board_detail,:image_detail,class:'user-show-board'%>
          </div>
        </div>
      <% end %>
      <hr>
      <div class="Heading">
        <p>最後に</p>
      </div>
      <div class="show-form">
        <p><%= simple_format @board.point%></p>
      </div>
      <hr>
      <% if @board.user.id == current_user.id %>
      <div class="edit-delete-btn">
        <%= link_to edit_board_path(@board),class:'btn btn-info' do%>
          編集
        <% end %>
        <%= link_to "削除", board_path(@board),method: :delete,
        data: {confirm: "削除しますか？"},
        class:'btn btn-danger delete'%>
      </div>
      <% else %>
        <div class="Heading">
          <p>レビューを投稿する</p>
        </div>
        <div class="review_container">
          <%= render 'reviews/form', review: @review, board: @board%>
        </div>
      <% end %>
  </div>
  <hr>
  <div class="Heading">
    <p>投稿者の声</p>
  </div>
  <% @reviews.each do |review| %>
  <div class="review-past">
    <div class="speech">
      <div class="review-created">
        <%= review.created_at.strftime("%Y-%m-%d %H:%M") %>
      </div>
          <div class="star-rating">
            <div class=" star-rating-front" style="width: <%= review.score * 10 %>%">★★★★★</div>
            <div class=" star-rating-back">★★★★★</div>
          </div>
      <div class="review-title">
        〜<%= review.review_title%>〜
      </div>
      <div class="review-content">
        <%= review.content%>
      </div>
      <div class="review-user-image">
        <%= attachment_image_tag review, :review_image%>
      </div>

    </div>
      <div class="blank"></div>
    <div class="review-user-profile">
      <%= attachment_image_tag review.user, :profile_image,fallback: "No-Image.png"%>
    </div>
    <div class="review-user-name">
      <span>
        <%= review.user.name%>
      </span>
    </div>
  </div>
  <% end %>
  
</div>